<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="scenes\" />
    <Folder Include="scenes\level_scenes\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="scripts\ui\Item.cs" />
    <Compile Remove="scripts\level_scripts\npcs\**" />
    <Compile Remove="scenes\ui\**" />
    <Compile Remove="scripts\action_components\projectile_action_components\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="scripts\level_scripts\npcs\**" />
    <EmbeddedResource Remove="scenes\ui\**" />
    <EmbeddedResource Remove="scripts\action_components\projectile_action_components\**" />
  </ItemGroup>
</Project>